### Agenda
- Revision
- Numpy Library - Arrays
- Matplotlib  - Visualization
- Pandas - Dataframe
- Seaborn and pandas
- plotly library + dash(framework using flask)

### Python Revision

###### Ex. Apply 7% service charge to all the sales values in the given tuple

In [1]:
sales = ("290", "300", "800", "500")
[int(i) * 1.07 for i in sales]    

[310.3, 321.0, 856.0, 535.0]

###### Ex. Sort the folowing list of words based on number of characters in each word

In [6]:
words = ["flight", "car", "bike", "train"]
sorted(words, key = len  # passing function object of len() as argument

['car', 'bike', 'train', 'flight']

###### Ex. Sort the dict based on salaries

In [5]:
emp = {"Jane" : 50000, "George" : 40000, "Jack" : 45000, "Rosie" : 25000}
sorted(emp, key = lambda x : emp[x])

['Rosie', 'George', 'Jack', 'Jane']

In [8]:
sorted(emp.items())  # list of tuples sorted by first element of the tuple

[('George', 40000), ('Jack', 45000), ('Jane', 50000), ('Rosie', 25000)]

In [9]:
sorted(emp.items(), key = lambda val : val[1]) 

[('Rosie', 25000), ('George', 40000), ('Jack', 45000), ('Jane', 50000)]

In [10]:
dict(sorted(emp.items(), key = lambda val : val[1]) )

{'Rosie': 25000, 'George': 40000, 'Jack': 45000, 'Jane': 50000}

###### Ex. Convert the following list of numbers to its square roots

In [11]:
import math
numbers = [1, 4, 9, 16, 25]
[math.sqrt(i) for i in numbers]

[1.0, 2.0, 3.0, 4.0, 5.0]

In [13]:
tuple(map(math.sqrt, numbers))

(1.0, 2.0, 3.0, 4.0, 5.0)

###### Ex. Extract all digits from a string entered by user

In [14]:
string = input("Enter a string - ")
for ch in string :
    if ch.isdigit():
        print(ch)

Enter a string -  abcd1234


1
2
3
4


In [16]:
[ch for ch in string if ch.isdigit()]

['1', '2', '3', '4']

In [18]:
tuple(filter(lambda ch : ch.isdigit(), string))

('1', '2', '3', '4')

In [19]:
num = "123"
num.isdigit()  # called on str instance/object

True

In [20]:
str.isdigit(num)  # called on the str class and object is passed as argument

True

In [25]:
tuple(filter(str.isdigit, string))

('1', '2', '3', '4')

In [21]:
class Circle :

    def __init__(self, radius) :
        self.radius = radius

    def area(self) :
        return 3.14 * self.radius * self.radius

In [22]:
c = Circle(10)

In [23]:
c.area()

314.0

In [24]:
Circle.area(c)

314.0

## Functions in Python

In [31]:
# Function defination
def factorial(num) :  # num - parameters 
    fact = 1
    for i in range(num, 1, -1) :
        fact *= i
    return fact   # return statement

In [32]:
factorial(5)  # 5 - argument to function call

120

#### Function returning multiple values as a tuple object

In [33]:
def func(num) :
    sq = num **2
    cube = num **3
    return sq, cube  # packing of tuples

In [37]:
x, y = func(5)  # unpacking of tuples
y

125

In [36]:
x

25

In [39]:
# defining multiple variables in a single line - 
x, y = 10, 20  # packing and unpacking of tuples

In [45]:
# application of unpacking of tuples
for i, j in emp.items() :
    print(i, " - ", j)

Jane  -  50000
George  -  40000
Jack  -  45000
Rosie  -  25000


#### Function Arguments

1. Required Positional Argument
2. Default Argument
3. Variable Length Argument
4. Key-word Argument
5. Variable Length Key-word Argument

#### Required Positional Argument

In [6]:
def demo(name, age) :
    print(f"Name - {name} | Age - {age}.")
    
demo("Jane", 30)
demo(30, "Jane")
demo("Jane")  # Error

Name - Jane | Age - 30.
Name - 30 | Age - Jane.


TypeError: demo() missing 1 required positional argument: 'age'

###### Example - 

In [7]:
help(list.insert)

Help on method_descriptor:

insert(self, index, object, /) unbound builtins.list method
    Insert object before index.



In [9]:
lst = [10, 20, 30, 40]
lst.insert(2, 4)  # 4 inserted at position 2
print(lst)

[10, 20, 4, 30, 40]


In [10]:
lst = [10, 20, 30, 40]
lst.insert(4, 2)  # 2 inserted at position 4
print(lst)

[10, 20, 30, 40, 2]


In [11]:
lst = [10, 20, 30, 40]
lst.insert("abcd", 2)  # 2 inserted at position 4
print(lst)

TypeError: 'str' object cannot be interpreted as an integer

#### Default Argument

In [16]:
def demo(name, age = 25) :
    print(f"Name - {name} | Age - {age}.")
    
demo("Jane", 30)
demo(30, "Jane")
demo("Jane")
demo()

Name - Jane | Age - 30.
Name - 30 | Age - Jane.
Name - Jane | Age - 25.


TypeError: demo() missing 1 required positional argument: 'name'

###### Example - 

In [12]:
help(str.replace)

Help on method_descriptor:

replace(self, old, new, count=-1, /) unbound builtins.str method
    Return a copy with all occurrences of substring old replaced by new.

      count
        Maximum number of occurrences to replace.
        -1 (the default value) means replace all occurrences.

    If the optional argument count is given, only the first count occurrences are
    replaced.



In [13]:
word = "mississippi"
word.replace("i", "*")

'm*ss*ss*pp*'

In [14]:
word = "mississippi"
word.replace("i", "*", 2)

'm*ss*ssippi'

#### Variable Length Argument

In [18]:
def demo(name, *args, age = 25) :
    print(f"Name - {name} | Age - {age} | Args - {args}")
    
demo("Jane", 10, 20, 30, 40, 50, 19)

Name - Jane | Age - 25 | Args - (10, 20, 30, 40, 50, 19)


###### Example - 

In [23]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [27]:
a = 10
b = 5
c = 15
print("Addition of", a, "and", b, "=", c)

Addition of 10 and 5 = 15


In [25]:
print("Addition of", a, "and", b, "=", c, sep = "_")

Addition of_10_and_5_=_15


#### Key-word Argument

In [21]:
def demo(name, *args, age = 25) :
    print(f"Name - {name} | Age - {age} | Args - {args}")
    
demo("Jane", 10, 20, 30, 40, 50, age = 19)

Name - Jane | Age - 19 | Args - (10, 20, 30, 40, 50)


#### Variable Length Key-word Argument

In [22]:
def demo(name, *args, age = 25, **kwargs) :
    print(f"Name - {name} | Age - {age} | Args - {args} | kwargs - {kwargs}")
    
demo("Jane", 10, 20, 30, 40, 50, age = 19, gender = "F", mob = 987654321)

Name - Jane | Age - 19 | Args - (10, 20, 30, 40, 50) | kwargs - {'gender': 'F', 'mob': 987654321}


#### Application of packing and unpacking of tuples wrt function calls

In [ ]:
def demo(name, *args, age = 25) :
    print(f"Name - {name} | Age - {age} | Args - {args}")
    
demo("Jane", 10, 20, 30, 40, 50, age = 19)  # packing of tuples to args

###### Ex - Writing from from a list of tuples to a a file using predefined function

In [36]:
# pre-defined function with no edit access
def write_to_file(name, age, gender):
    with open("details.txt", "a") as file :
        file.write(f"{name} | {age} | {gender}\n")
        print(f"Details for {name} added to the file.")

In [37]:
data = [("Jane", 35, "F"),
    ("Rosie", 30, "F"),
    ("George", 40, "M")]

for i in data :
    write_to_file(*i)  # unpacking of tuples

Details for Jane added to the file.
Details for Rosie added to the file.
Details for George added to the file.


In [38]:
data = {"name" : "Jack", "gender" : "M", "age" : 40 }
write_to_file(**data)  # unpacking of dict

Details for Jack added to the file.


#### Significance of `/` and `*` in function definition

- **`/`** - All arguments before `/` must be positional only
- **`*`** - All arguments after `*` must be key-word only

In [42]:
def demo(name, age= 25):
     print(f"Name - {name} | Age - {age}")

demo("Jane", 30) # positional 
demo(name = "Jane", age = 30) # key-word
demo("Jane", age = 30) # positional and key-word

Name - Jane | Age - 30
Name - Jane | Age - 30
Name - Jane | Age - 30


In [48]:
def demo(name, /, age):
     print(f"Name - {name} | Age - {age}")

demo("Jane", 30) 
demo("Jane", age = 30) 
demo(name = "Jane", age = 30) # Error

Name - Jane | Age - 30
Name - Jane | Age - 30


TypeError: demo() got some positional-only arguments passed as keyword arguments: 'name'

###### Example - 

In [40]:
help(str.replace)

Help on method_descriptor:

replace(self, old, new, count=-1, /) unbound builtins.str method
    Return a copy with all occurrences of substring old replaced by new.

      count
        Maximum number of occurrences to replace.
        -1 (the default value) means replace all occurrences.

    If the optional argument count is given, only the first count occurrences are
    replaced.



In [49]:
def demo(name, *, age):
     print(f"Name - {name} | Age - {age}")

demo("Jane", age = 30) 
demo(name = "Jane", age = 30) 
demo("Jane", 30) # Error

Name - Jane | Age - 30
Name - Jane | Age - 30


TypeError: demo() takes 1 positional argument but 2 were given

In [39]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



<hr><hr>

# Basics of NumPy
- NumPy - Introduction and Installation
- NumPy - Arrays Data Structure ( 1D, 2D, ND arrays)
- Creating Arrays
- NumPy - Data Types
- Array Attributes
- Creating Arrays – Alternative Ways
- Sub-setting, Slicing and Indexing Arrays
- Operations on Arrays
- Array Manipulation


### NumPy – Introduction and Installation

- NumPy stands for ‘Numeric Python’
- Used for mathematical and scientific computations
- NumPy array is the most widely used object of the NumPy library

#### Installing numpy

In [ ]:
pip install numpy
pip install pandas
pip install matplotlib
pip install seaborn

#### Importing numpy

In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Arrays Data Structure

An `Array` is combination of homogenous data objects and can be indexed across multiple dimensions

#### Arrays are –
- ordered sequence/collection of Homogenous data
- multidimensional
- mutable


#### Creating Arrays – From list/tuple

- `np.array()` is used to create a numpy array from a list


#### Example on 1-D Array

In [51]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

#### Example on 2-D Array

In [52]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Array Attributes

- Attributes are the features/characteristics of an object that describes the object

- Some of the attributes of the numpy array are:
    - **shape** - Array dimensions
    - **size** - Number of array elements
    - **dtype** - Data type of array elements
    - **ndim** - Number of array dimensions
    - **dtype.name** - Name of data type
    - **astype** - Convert an array to a different type


In [53]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr.shape  # - (row, cols)

(3, 4)

In [55]:
arr.size

12

In [56]:
arr.ndim

2

In [57]:
arr.dtype

dtype('int64')

In [ ]:
arr.astype(float)

### Indexing, Slicing and Boolen Indexing

In [58]:
arr = np.random.randint(5, 50, size = 10)
arr

array([14, 13, 48, 15, 17,  7, 25, 24, 19, 38], dtype=int32)

#### 1-D Arrays

###### Ex. Extract first 3 elements

In [59]:
arr[0:3]

array([14, 13, 48], dtype=int32)

###### Ex. Extract last 5 elements

In [60]:
arr[-5 : ]

array([ 7, 25, 24, 19, 38], dtype=int32)

###### Ex. Extract element at position 2

In [61]:
arr[2]  # indexing

np.int32(48)

###### Ex. Extract elements at index position 2, 5, 9.

In [63]:
arr[[2, 9, 5]]

array([48, 38,  7], dtype=int32)

###### Ex. Extract elements less than 20

In [64]:
arr < 20  # returns a bool array

array([ True,  True, False,  True,  True,  True, False, False,  True,
       False])

In [65]:
arr[arr < 20 ] # conditional indexing

array([14, 13, 15, 17,  7, 19], dtype=int32)

### 2-D Arrays

In [66]:
arr = np.random.randint(5, 50, size = (6,4))
arr

array([[27, 14, 26, 32],
       [35, 35,  8, 28],
       [42, 11, 42, 34],
       [23, 34, 49, 47],
       [21, 20, 16, 21],
       [41, 11,  9, 33]], dtype=int32)

###### Ex. Extract first 3 rows

In [67]:
arr[0:3]

array([[27, 14, 26, 32],
       [35, 35,  8, 28],
       [42, 11, 42, 34]], dtype=int32)

###### Ex. Extract last 2 rows

In [68]:
arr[-2 :]

array([[21, 20, 16, 21],
       [41, 11,  9, 33]], dtype=int32)

###### Ex. Extract column at index 1

In [69]:
arr[ : , 1]  # returns 1D array

array([14, 35, 11, 34, 20, 11], dtype=int32)

###### Ex. Extract row 2 and 3 and column 2 and 3 (index-wise)

In [70]:
arr[2:4, 2:4]

array([[42, 34],
       [49, 47]], dtype=int32)

###### Ex. Extract values less than 25

In [72]:
arr[arr < 25]  # returns 1D array

array([14,  8, 11, 23, 21, 20, 16, 21, 11,  9], dtype=int32)

###### Ex. Identify largest value. Extract values less than half of largest values

In [75]:
arr[arr <= arr.max()/2]

array([14,  8, 11, 23, 21, 20, 16, 21, 11,  9], dtype=int32)

### Examples on Coffee Shop Data Set

#### Ex.  Create an array of coffee products, sales and profits

In [76]:
coffee_products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array( [52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])

###### Ex. How many products are there in the dataset?

In [77]:
coffee_products.size

10

###### Ex.  Sales greater than 50,000

In [78]:
sales[sales > 50000]

array([52248., 71060., 60014., 69925.])

In [79]:
coffee_products[sales > 50000]

array(['Caffe Latte', 'Colombian', 'Darjeeling', 'Decaf Irish Cream'],
      dtype='<U17')

###### Ex.  Identify Losses

In [80]:
profits[profits < 0]

array([-2954.])

###### Ex.  Products in loss

In [81]:
coffee_products[profits < 0]

array(['Green Tea'], dtype='<U17')

###### Ex.  Product with maximum Sales

In [82]:
coffee_products[sales == sales.max()]

array(['Colombian'], dtype='<U17')

In [83]:
coffee_products[sales == sales.max()][0]

np.str_('Colombian')

### Array Operations

#### Arithmetic operations on Arrays -
 - Addition, Substraction, Multiplication, Division, etc.
 - Operations on array and a scalar value
 - Operations between two arrays
 - Matrix Operations - Multiplication(np.dot()), Transpose(np.transpose())


#### Array and Scalar

In [84]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([6, 3, 6, 9, 2], dtype=int32)

In [85]:
arr1 + 5 # Addition

array([11,  8, 11, 14,  7], dtype=int32)

In [86]:
arr1 - 5 # Substraction

array([ 1, -2,  1,  4, -3], dtype=int32)

In [87]:
arr1 * 5 # Multiplication

array([30, 15, 30, 45, 10], dtype=int32)

In [88]:
arr1 / 5 # Division

array([1.2, 0.6, 1.2, 1.8, 0.4])

In [89]:
arr1 // 5 # Floor Division

array([1, 0, 1, 1, 0], dtype=int32)

In [90]:
arr1 % 5 # Modulus

array([1, 3, 1, 4, 2], dtype=int32)

#### Two Arrays

In [91]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([2, 9, 5, 8, 7], dtype=int32)

In [92]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([8, 1, 1, 6, 5], dtype=int32)

In [93]:
arr1 + arr2 # Addition

array([10, 10,  6, 14, 12], dtype=int32)

In [94]:
arr1 - arr2 # Substraction

array([-6,  8,  4,  2,  2], dtype=int32)

In [95]:
arr1 * arr2 # Multiplication

array([16,  9,  5, 48, 35], dtype=int32)

In [96]:
arr1 / arr2 # Division

array([0.25      , 9.        , 5.        , 1.33333333, 1.4       ])

In [97]:
arr1 // arr2 # Floor Division

array([0, 9, 5, 1, 1], dtype=int32)

In [98]:
arr1 % arr2 # Modulus

array([2, 0, 0, 2, 2], dtype=int32)

#### Relational operations on Arrays -
 - ==, !=, <, >, <=, >=
 - Operations on array and a scalar value
 - Operations between two arrays

#### Array and Scalar

In [100]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([4, 7, 2, 2, 3], dtype=int32)

In [101]:
arr1 == 5

array([False, False, False, False, False])

In [102]:
arr1 != 5

array([ True,  True,  True,  True,  True])

In [103]:
arr1 < 5

array([ True, False,  True,  True,  True])

In [104]:
arr1 > 5

array([False,  True, False, False, False])

In [105]:
arr1 <= 5

array([ True, False,  True,  True,  True])

In [106]:
arr1 >= 5

array([False,  True, False, False, False])

#### Two Arrays

In [107]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([6, 6, 3, 5, 8], dtype=int32)

In [108]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([4, 8, 7, 5, 3], dtype=int32)

In [109]:
arr1 == arr2

array([False, False, False,  True, False])

In [110]:
arr1 != arr2

array([ True,  True,  True, False,  True])

In [111]:
arr1 < arr2

array([False,  True,  True, False, False])

In [112]:
arr1 > arr2

array([ True, False, False, False,  True])

In [113]:
arr1 <= arr2

array([False,  True,  True,  True, False])

In [114]:
arr1 >= arr2

array([ True, False, False,  True,  True])

#### Logical operations on Arrays -
 - np.logical_or()
 - np.logical_and()
 - np.logical_not()
 - np.logical_xor()

In [115]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([6, 7, 8, 1, 2], dtype=int32)

In [116]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([1, 7, 5, 4, 2], dtype=int32)

In [117]:
np.logical_and(arr1 > 5, arr2 > 5)

array([False,  True, False, False, False])

In [118]:
np.logical_or(arr1 > 5, arr2 > 5)

array([ True,  True,  True, False, False])

In [119]:
np.logical_not(arr1 > 5)

array([False, False, False,  True,  True])

In [120]:
np.logical_xor(arr1 > 5, arr2 > 5)

array([ True, False,  True, False, False])

#### Set Operations on Arrays

Applicable to 1-D Ararys only

- np.unique() - Find the unique elements of an array.
- np.in1d() - Test whether each element of a 1-D array is also present in a second array.
- np.intersect1d() - Find the intersection of two arrays.
- np.setdiff1d() - Find the set difference of two arrays.
- np.union1d() - Find the union of two arrays.

In [121]:
arr1 = np.random.randint(1, 10, size = 10)
arr1

array([8, 2, 7, 5, 1, 7, 5, 8, 9, 3], dtype=int32)

In [122]:
np.unique(arr1)

array([1, 2, 3, 5, 7, 8, 9], dtype=int32)

In [124]:
np.unique(arr1, return_index= True, return_counts=True)

(array([1, 2, 3, 5, 7, 8, 9], dtype=int32),
 array([4, 1, 9, 3, 2, 0, 8]),
 array([1, 1, 1, 2, 2, 2, 1]))

In [125]:
arr2 = np.random.randint(1, 5, size = 10)
arr2

array([2, 4, 1, 3, 4, 1, 2, 3, 2, 3], dtype=int32)

In [126]:
np.in1d(arr1, arr2)  # depricated in 3.12 onwards

C:\Users\vaide\AppData\Local\Temp\ipykernel_29828\2696172370.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr1, arr2)  # depricated in 3.12 onwards


array([False,  True, False, False,  True, False, False, False, False,
        True])

In [127]:
np.isin(arr1, arr2)  # alternate for in1d()

array([False,  True, False, False,  True, False, False, False, False,
        True])

In [128]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 7, 8, 9], dtype=int32)

In [129]:
np.intersect1d(arr1, arr2)

array([1, 2, 3], dtype=int32)

### Array Functions/Methods

- np.all(), np.any()
- arr.sum()
- arr.min(), arr.max(), arr.argmin(), arr.agrmax()
- np.round()
- np.mean(), np.median(), np.average(), np.percentile()


In [145]:
age = np.random.randint(22, 60, size = 50)
age

array([36, 46, 26, 22, 42, 45, 35, 26, 42, 50, 55, 43, 32, 59, 29, 54, 26,
       34, 41, 46, 41, 31, 38, 39, 56, 47, 39, 34, 54, 28, 46, 55, 34, 35,
       51, 42, 47, 31, 42, 24, 27, 37, 32, 40, 26, 52, 29, 47, 22, 43],
      dtype=int32)

In [140]:
age.sum()

np.int64(1853)

In [141]:
np.sum(age)

np.int64(1853)

In [146]:
np.mean(age)  # Average age of perople in the dataset

np.float64(39.16)

In [147]:
np.std(age) # Deviation from the mean

np.float64(9.825192110081105)

In [148]:
np.min(age)

np.int32(22)

In [149]:
np.max(age)

np.int32(59)

In [150]:
np.median(age) # 50% of employees are less than 39 yrs and 50 % are greater than 39 yrs

np.float64(39.5)

In [152]:
np.percentile(age, 25)  # 25% of employees are less than 31 yrs and 75 % are greater than 31 yrs

np.float64(31.25)

In [154]:
np.percentile(age, 75)  # 75% of employees are less than 46 yrs and 25 % are greater than 46 yrs

np.float64(46.0)

In [156]:
from scipy.stats import mode
mode(age)

ModeResult(mode=np.int32(26), count=np.int64(4))

In [157]:
mode(age).mode

np.int32(26)

In [158]:
mode(age).count

np.int64(4)

In [161]:
np.argmin(age) # index position of first occurence of the min value

np.int64(3)

In [162]:
np.argmax(age) # index position of first occurence of the max value

np.int64(13)

###### Ex. Find product with max sales

In [163]:
coffee_products[sales == max(sales)]  # conditional indexing/filtering - returns array object

array(['Colombian'], dtype='<U17')

In [164]:
coffee_products[np.argmax(sales)]  # indexing - returns str object

np.str_('Colombian')

###### Ex. Check if all elements are greater than 5

In [132]:
np.all(arr1 > 5)

np.False_

###### Ex. Check if any one element is greater than 5

In [133]:
np.any(arr1 > 5)

np.True_

### Array Manipulations

- **Changing Shape** – np.reshape()
- **Adding/Removing Elements** – np.append(), np.insert(), np.delete()
- **Splitting Arrays** – np.hsplit(), np.vsplit(), arr_obj.flatten()
- **Sorting Arrays** - arr_obj.sort(), arr_obj.argsort()

In [165]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### np.reshape()

In [166]:
arr = np.reshape(arr, (4, 3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.append()

In [167]:
np.append(arr, [10,20,30, 50, 40, 60]) # Flattens the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 10, 20, 30, 50, 40,
       60])

In [171]:
np.append(arr, np.reshape(np.array([13, 14, 15]), (1, 3)), axis = 0) # axis = 0 denotes row-wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [173]:
np.append(arr, np.reshape(np.array([10, 20, 30, 40]), (4, 1)), axis = 1) # axis = 1 denotes col-wise

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30],
       [10, 11, 12, 40]])

#### np.insert()

In [174]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [175]:
np.insert(arr, 1, 5) # Flattens the arr and inserts 5 at index 1

array([ 1,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [176]:
np.insert(arr, 1, 5, axis=0) # Inserts [5, 5, 5] as row 1

array([[ 1,  2,  3],
       [ 5,  5,  5],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [177]:
np.insert(arr, 1, 5, axis=1) # Inserts [5, 5, 5, 5] as column 1

array([[ 1,  5,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  5,  8,  9],
       [10,  5, 11, 12]])

In [178]:
np.insert(arr, 1, [10, 20, 30, 40], axis=1)

array([[ 1, 10,  2,  3],
       [ 4, 20,  5,  6],
       [ 7, 30,  8,  9],
       [10, 40, 11, 12]])

In [179]:
np.insert(arr, 1, [10, 20, 30], axis=0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.delete()

In [180]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [181]:
np.delete(arr, 1) # Flattens the arr and deletes element at index 1

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [182]:
np.delete(arr, 1, axis=0) # deletes row 1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [183]:
np.delete(arr, 1, axis=1) # deletes column 1

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [184]:
np.delete(arr,[0,2], axis=0) # deletes selected rows

array([[ 4,  5,  6],
       [10, 11, 12]])

In [185]:
np.delete(arr,[0,2], axis=1) # deletes selected columns

array([[ 2],
       [ 5],
       [ 8],
       [11]])

#### np.hsplit(), np.vsplit()

In [186]:
arr = np.reshape(np.arange(1, 25), (6,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [187]:
np.vsplit(arr, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [188]:
np.hsplit(arr, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

#### flatten()

In [189]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [190]:
arr.flatten() # returns a 1-D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [191]:
arr.flatten(order = "F") # returns a 1-D array

array([ 1,  5,  9, 13, 17, 21,  2,  6, 10, 14, 18, 22,  3,  7, 11, 15, 19,
       23,  4,  8, 12, 16, 20, 24])

In [ ]:
help(arr.flatten)

#### np.sort()

In [192]:
coffee_products

array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling',
       'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint',
       'Regular Espresso'], dtype='<U17')

In [193]:
sales

array([52248., 14068., 71060., 60014., 69925., 27711., 19231., 24873.,
       32825., 44109.])

In [ ]:
sales.sort() # modify original arr

In [194]:
np.sort(sales)  # generates new array

array([14068., 19231., 24873., 27711., 32825., 44109., 52248., 60014.,
       69925., 71060.])

###### Ex. Sort coffee products based on sales

In [195]:
np.argsort(sales)  # returns the index position of original elements in sorted order

array([1, 6, 7, 5, 8, 9, 0, 3, 4, 2])

In [198]:
coffee_products[np.argsort(sales)]

array(['Cappuccino', 'Green Tea', 'Lemon', 'Earl Grey', 'Mint',
       'Regular Espresso', 'Caffe Latte', 'Darjeeling',
       'Decaf Irish Cream', 'Colombian'], dtype='<U17')

### Examples on Coffee Shop Data Set

In [199]:
import numpy as np
products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array([52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])
target_profits = np.array([15934.0, 4924.0, 31814.0, 19649.0, 24934.0, 8461.0, 7090.0, 7084.0, 10135.0, 16306.0])
target_sales = np.array([48909.0, 13070.0, 80916.0, 57368.0, 66906.0, 30402.0, 18212.0, 21628.0, 27336.0, 42102.0])

###### Ex. Identify the products meeting the Target Profits

In [201]:
profit_ach = products[profits >= target_profits]
profit_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Lemon', 'Mint'],
      dtype='<U17')

###### Ex. Are the above products meeting their sales target too?

In [202]:
sales_ach = products[sales >= target_sales]
sales_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Decaf Irish Cream',
       'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'], dtype='<U17')

In [205]:
if np.isin(profit_ach, sales_ach).all() :
    print("yes")
else:
    print("no")

yes


In [208]:
if np.isin(sales_ach, profit_ach).all() :
    print("yes")
else:
    print("no. some products achieveing sales target but not profit target")
    print(np.setdiff1d(sales_ach, profit_ach))

no. some products achieveing sales target but not profit target
['Decaf Irish Cream' 'Green Tea' 'Regular Espresso']


###### Ex. Identify products which are not achieving their profit target. Calculate their target status in percentage. Display the products in DESC order of their percentage status

In [217]:
products_def = products[target_profits > profits]
profits_def = profits[target_profits > profits]
target_def = target_profits[target_profits > profits]

percentage = np.round(profits_def/target_def * 100, 2)
percentage[percentage < 0 ] = 0
percentage

array([89.24, 93.98, 90.9 ,  0.  , 91.39])

In [219]:
for prod, per in zip(products_def, percentage) :
    print(f"{prod} has achieved {per}% of total profits.")

Colombian has achieved 89.24% of total profits.
Decaf Irish Cream has achieved 93.98% of total profits.
Earl Grey has achieved 90.9% of total profits.
Green Tea has achieved 0.0% of total profits.
Regular Espresso has achieved 91.39% of total profits.


<hr><hr>